/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Facade.Administrador;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author donramon
 */
public class VAdminDarDeBajaJugador extends javax.swing.JFrame {
    
    
    private JFrame ventanaAnterior;
    private Administrador administrador;
    private ArrayList<String> jugadores;
    private DefaultListModel modeloLista;
    private Object jugador;
    public VAdminDarDeBajaJugador(JFrame ventanaAnterior, Administrador administrador, ArrayList<String> jugadores) 
    {
        this.administrador = administrador;
        this.ventanaAnterior = ventanaAnterior;
        
        this.jugadores = jugadores;
        initComponents();
        
        modeloLista = new DefaultListModel();
        darBajaJugador.setModel(modeloLista);

        for (Object item : jugadores) 
            modeloLista.addElement(item);
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labJug = new javax.swing.JLabel();
        listJug = new javax.swing.JScrollPane();
        darBajaJugador = new javax.swing.JList<>();
        botAtras = new javax.swing.JButton();
        darDeBaja = new javax.swing.JButton();

        labJug.setText("Selecciona al jugador que quieres dar de baja");

        listJug.setViewportView(darBajaJugador);

        botAtras.setText("Atrás");
        botAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtrasActionPerformed(evt);
            }
        });

        darDeBaja.setText("Dar de baja");
        darDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darDeBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(darDeBaja)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labJug)
                        .addGap(114, 114, 114))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(listJug, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(labJug, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listJug, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAtras)
                    .addComponent(darDeBaja))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtrasActionPerformed
        this.setVisible(false);
        ventanaAnterior.setVisible(true);
    }//GEN-LAST:event_botAtrasActionPerformed

    private void darDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darDeBajaActionPerformed
        
        jugador = darBajaJugador.getSelectedValue();
        
        if(jugador != null)
        {
            try {
                administrador.darDeBajaJugador((String)jugador);
                jugadores.remove((String)jugador);
                modeloLista.removeElement(jugador);
                
                JOptionPane.showMessageDialog(null,"El usuario " + (String)jugador+" ha sido dado de baja correctamente.");
                
                if(jugadores.size() == 0)
                {
                    JOptionPane.showMessageDialog(null, "No hay más usuarios.", "¡Usuarios!", JOptionPane.WARNING_MESSAGE);
                    this.setVisible(false);
                    ventanaAnterior.setVisible(true);
                }
                    
                
            } catch (IOException ex) {
                Logger.getLogger(VAdminDarDeBajaJugador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Primero debe seleccionar a un usuario.", "¡Selecciona usuarios!", JOptionPane.WARNING_MESSAGE);
        }
             
    }//GEN-LAST:event_darDeBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAtras;
    private javax.swing.JList<String> darBajaJugador;
    private javax.swing.JButton darDeBaja;
    private javax.swing.JLabel labJug;
    private javax.swing.JScrollPane listJug;
    // End of variables declaration//GEN-END:variables
}
