/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Facade.Administrador;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author donramon
 */
public class VCrearTorneo extends javax.swing.JFrame{
   
    /**
     * Creates new customizer VentanaCrearTorneo
     */
    private JFrame ventanaAnterior;
    private Administrador administrador;
    private DefaultListModel modeloLista, modeloListaJugador;
    private ArrayList<String> sedes;
    private ArrayList<String> jugadores;
    private Object sede, jugador;
    private añadirJugadoresSedes añadirJugador;
    
    public VCrearTorneo(JFrame ventanaAnterior, Administrador administrador, añadirJugadoresSedes añadirJugador, ArrayList<String> jugadores) {
        this.ventanaAnterior = ventanaAnterior;
        this.administrador = administrador;
        this.añadirJugador = añadirJugador;
        this.jugadores = jugadores;
        
        sedes = administrador.getSedes();
        
       
        
        initComponents();
        
        if(jugadores.size() == 0)
            jButton1.setEnabled(false);
            
        modeloLista = new DefaultListModel();
        modeloListaJugador = new DefaultListModel();
        listaSede.setModel(modeloLista);
        listaJugadores.setModel(modeloListaJugador);
       
       for (Object item : sedes) 
          modeloLista.addElement(item);
        
        for (Object item : jugadores) 
            modeloListaJugador.addElement(item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSede = new javax.swing.JList<>();
        labListSed = new javax.swing.JLabel();
        labListJug = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        botAtras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        añadirSede = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jScrollPane1.setViewportView(listaSede);

        labListSed.setText("Selecciona la sede participantes en el torneo");

        labListJug.setText("Selecciona los jugadores participantes en el torneo");

        jScrollPane2.setViewportView(listaJugadores);

        botAtras.setText("Atrás");
        botAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtrasActionPerformed(evt);
            }
        });

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        añadirSede.setText("Añadir");
        añadirSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botAtras)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(añadirSede))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labListSed)
                                .addGap(100, 100, 100)))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(246, 246, 246))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(labListJug)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(labListSed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(añadirSede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(labListJug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(10, 10, 10)
                .addComponent(botAtras)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtrasActionPerformed
        this.setVisible(false);
        añadirJugador.setVisible(false);
        ventanaAnterior.setVisible(true);
        
    }//GEN-LAST:event_botAtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jugador = listaJugadores.getSelectedValue();
        if(jugador != null)
       {    
           añadirJugador.añadirJugador(jugador);
       }
       else
           JOptionPane.showMessageDialog(null,"Selecciona el jugador");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void añadirSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirSedeActionPerformed
        sede = listaSede.getSelectedValue();
        if(sede != null)
        {
           añadirJugador.añadirSede(sede);
        }
    }//GEN-LAST:event_añadirSedeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirSede;
    private javax.swing.JButton botAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labListJug;
    private javax.swing.JLabel labListSed;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JList<String> listaSede;
    // End of variables declaration//GEN-END:variables
}
