/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Facade.Administrador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DatosClub;

/**
 *
 * @author donramon
 */
public class VDarBajaClub extends javax.swing.JFrame {
    
    private JFrame ventanaAnterior;
    private Administrador admin;
    private DefaultListModel listaMoClub;
    
    public VDarBajaClub(JFrame ventanaAnterior, Administrador administrador) throws SQLException {
        this.ventanaAnterior = ventanaAnterior;
        this.admin = administrador;
        initComponents();
        comprobarClub();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listClub = new javax.swing.JList<>();
        labTexClub = new javax.swing.JLabel();
        botAtras = new javax.swing.JButton();
        botAceptar = new javax.swing.JButton();

        listClub.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listClub);

        labTexClub.setText("Selecciona el club que quieras dar de baja");

        botAtras.setText("Atrás");
        botAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtrasActionPerformed(evt);
            }
        });

        botAceptar.setText("Aceptar");
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labTexClub)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(botAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botAceptar)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labTexClub)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botAtras)
                    .addComponent(botAceptar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtrasActionPerformed
        this.setVisible(false);
        ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botAtrasActionPerformed

    private void botAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAceptarActionPerformed
        try {
            admin.eliminarClub(listClub.getSelectedValue());
            JOptionPane.showMessageDialog(null,"Se ha eliminado el club","Confirmación",JOptionPane.DEFAULT_OPTION);
            comprobarClub();
        } catch (SQLException ex) {
            Logger.getLogger(VDarBajaClub.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botAceptarActionPerformed
private void comprobarClub() throws SQLException
{
       if(!admin.getClubs().isEmpty())
        {
            this.setSize(400, 300);
            this.setVisible(true);
            this.setLocationRelativeTo(null);
            this.setResizable(false);
            this.setTitle("Baja club");
        
            listaMoClub = new DefaultListModel();

            listClub.setModel(listaMoClub);

            for(DatosClub item:admin.getClubs())
               listaMoClub.addElement(item);
        }
        else
        {
            this.setVisible(false); 
            JOptionPane.showMessageDialog(null,"No hay ningún Club creado","Atención",JOptionPane.WARNING_MESSAGE);
            ventanaAnterior.setVisible(true);
            this.dispose();
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JButton botAtras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labTexClub;
    private javax.swing.JList<String> listClub;
    // End of variables declaration//GEN-END:variables
}
