/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Facade.Administrador;
import Facade.Jugador;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayoub El Moussaoui
 */
public class ventanaPrincipal extends javax.swing.JFrame {

    private JFrame ventanaAnterior;
    private String usuario;
    private Jugador jugador;
    private Administrador administrador;
    public ventanaPrincipal(JFrame ventanaAnterior, String usuario, Jugador jugador, Administrador administrador) {
        this.ventanaAnterior = ventanaAnterior;
        this.usuario = usuario;
        this.jugador = jugador;
        this.administrador = administrador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarEquipo = new javax.swing.JButton();
        apuntarseTorneo = new javax.swing.JButton();
        verTarjeta = new javax.swing.JButton();
        darseDeBaja = new javax.swing.JButton();
        reservarSede = new javax.swing.JButton();
        introducirResultado = new javax.swing.JButton();
        cerrarSesión = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscarEquipo.setText("Buscar equipo");
        buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipoActionPerformed(evt);
            }
        });

        apuntarseTorneo.setText("Apuntarse a torneo");
        apuntarseTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apuntarseTorneoActionPerformed(evt);
            }
        });

        verTarjeta.setText("Ver tarjeta");
        verTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verTarjetaActionPerformed(evt);
            }
        });

        darseDeBaja.setText("Darse de baja");
        darseDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darseDeBajaActionPerformed(evt);
            }
        });

        reservarSede.setText("Reservar sede");
        reservarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarSedeActionPerformed(evt);
            }
        });

        introducirResultado.setText("Introducir resultado");
        introducirResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introducirResultadoActionPerformed(evt);
            }
        });

        cerrarSesión.setText("Cerrar sesión");
        cerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesiónActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(introducirResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(reservarSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(darseDeBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apuntarseTorneo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cerrarSesión))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(buscarEquipo)
                .addGap(18, 18, 18)
                .addComponent(apuntarseTorneo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verTarjeta)
                .addGap(18, 18, 18)
                .addComponent(darseDeBaja)
                .addGap(18, 18, 18)
                .addComponent(reservarSede)
                .addGap(18, 18, 18)
                .addComponent(introducirResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(cerrarSesión)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesiónActionPerformed

        this.setVisible(false); 
        ventanaAnterior.setVisible(true);

    }//GEN-LAST:event_cerrarSesiónActionPerformed

    private void apuntarseTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apuntarseTorneoActionPerformed
        apuntarseTorneo apuntarseTorneo = new apuntarseTorneo(this, administrador, usuario);
        this.setVisible(false); 
        apuntarseTorneo.setVisible(true);
        apuntarseTorneo.setLocationRelativeTo(null);
        apuntarseTorneo.setResizable(false);
        apuntarseTorneo.setTitle("Torneo");
    }//GEN-LAST:event_apuntarseTorneoActionPerformed

    private void verTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verTarjetaActionPerformed
        verTarjeta tarjeta = new verTarjeta(this, usuario, jugador);
        this.setVisible(false); 
        tarjeta.setVisible(true);
        tarjeta.setLocationRelativeTo(null);
        tarjeta.setResizable(false);
        tarjeta.setTitle("Tarjeta");
    }//GEN-LAST:event_verTarjetaActionPerformed

    private void darseDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darseDeBajaActionPerformed
            //JOptionPane.showMessageDialog(null,"¿Estas seguro?");
        int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que quiere darse de baja?", "¡Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
        
        if(resp == 0)
        {
            try {
                jugador.darDeBaja(usuario);
            } catch (IOException ex) {
                Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            ventanaAnterior.setVisible(true);
            JOptionPane.showMessageDialog(null, "La cuenta ha sido eliminada.");
        }
                        
    }//GEN-LAST:event_darseDeBajaActionPerformed

    private void reservarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarSedeActionPerformed
        reservaSede reservaSede = new reservaSede(this);
        this.setVisible(false); 
        reservaSede.setVisible(true);
        reservaSede.setLocationRelativeTo(null);
        reservaSede.setResizable(false);
        reservaSede.setTitle("Reserva sede");
    }//GEN-LAST:event_reservarSedeActionPerformed

    private void introducirResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introducirResultadoActionPerformed
        resultadoPartida resultadoPartida = new resultadoPartida(this);
        this.setVisible(false); 
        resultadoPartida.setVisible(true);
        resultadoPartida.setLocationRelativeTo(null);
        resultadoPartida.setResizable(false);
        resultadoPartida.setTitle("Resultado partida");
    }//GEN-LAST:event_introducirResultadoActionPerformed

    private void buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipoActionPerformed
        try {
            this.setVisible(false);
            buscarEquipo buscarEquipo = new buscarEquipo(this,administrador,usuario);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(ventanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarEquipoActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apuntarseTorneo;
    private javax.swing.JButton buscarEquipo;
    private javax.swing.JButton cerrarSesión;
    private javax.swing.JButton darseDeBaja;
    private javax.swing.JButton introducirResultado;
    private javax.swing.JButton reservarSede;
    private javax.swing.JButton verTarjeta;
    // End of variables declaration//GEN-END:variables
}
