/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.Administrador;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
//¿Este import se puede hacer?
import model.DatosGerente;

/**
 *
 * @author donramon
 */
public class VCamGerClub extends javax.swing.JFrame {
    
    /**
     * Creates new customizer VentanaCambiarGerenteClubAdmin
     */
    private DefaultListModel modeloListaClub;
    private DefaultListModel modeloListaGer;
    private Administrador administrador;
    private JFrame vetanaAnterior;
    
    public VCamGerClub(JFrame ventanaAnterior, Administrador administrador) {
        this.vetanaAnterior = ventanaAnterior;
        this.administrador = administrador;
        modeloListaClub = new DefaultListModel();
        modeloListaGer = new DefaultListModel();
        lisGerente.setModel(modeloListaClub);
        lisClub.setModel(modeloListaGer);
        initComponents();
        
        
        for(Object item:administrador.getClubs())
            modeloListaClub.addElement(item);
        
        for(Object item:administrador.getGerentes())
            modeloListaGer.addElement(item);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labGer = new javax.swing.JLabel();
        labClub = new javax.swing.JLabel();
        listGeren = new javax.swing.JScrollPane();
        lisGerente = new javax.swing.JList<>();
        listClub = new javax.swing.JScrollPane();
        lisClub = new javax.swing.JList<>();
        butAtras = new javax.swing.JButton();
        butAceptar = new javax.swing.JButton();

        labGer.setText("Gerente a cambiar");

        labClub.setText("Club a asignar");

        lisGerente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listGeren.setViewportView(lisGerente);

        lisClub.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listClub.setViewportView(lisClub);

        butAtras.setText("Atrás");

        butAceptar.setText("Aceptar");
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGer)
                    .addComponent(listGeren, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labClub, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(listClub))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butAceptar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labGer)
                    .addComponent(labClub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listGeren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butAtras)
                    .addComponent(butAceptar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        this.setVisible(false);
        vetanaAnterior.setVisible(true);
        administrador.getCambiaClub((Object)lisGerente.getSelectedValue(),(Object) lisClub.getSelectedValue());
    }//GEN-LAST:event_butAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butAtras;
    private javax.swing.JLabel labClub;
    private javax.swing.JLabel labGer;
    private javax.swing.JList<String> lisClub;
    private javax.swing.JList<String> lisGerente;
    private javax.swing.JScrollPane listClub;
    private javax.swing.JScrollPane listGeren;
    // End of variables declaration//GEN-END:variables
}
