/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author areba
 */
public class VCrearGerente extends javax.swing.JFrame {
VAdministrador vAnterior;
Administrador admin;
    /**
     * Creates new form VCrearGerente
     * @param vAnterior
     */
    public VCrearGerente(VAdministrador vAnterior, Administrador admin) {
        this.vAnterior = vAnterior; 
        this.admin = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabNom = new javax.swing.JLabel();
        jLabAp1 = new javax.swing.JLabel();
        jLabAp2 = new javax.swing.JLabel();
        jLabSex = new javax.swing.JLabel();
        jLabEdad = new javax.swing.JLabel();
        jLabNomin = new javax.swing.JLabel();
        jLabIRPF = new javax.swing.JLabel();
        jTexNom = new javax.swing.JTextField();
        jTexAp1 = new javax.swing.JTextField();
        jTexNomin = new javax.swing.JTextField();
        jTexAp2 = new javax.swing.JTextField();
        jTexEd = new javax.swing.JTextField();
        jTexIRPF = new javax.swing.JTextField();
        jBAcept = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jCoBSex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabNom.setText("Nombre :");

        jLabAp1.setText("Apellido 1:");

        jLabAp2.setText("Apellido 2:");

        jLabSex.setText("Sexo:");

        jLabEdad.setText("Edad:");

        jLabNomin.setText("Nomina:");

        jLabIRPF.setText("IRPF:");

        jTexNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexNomActionPerformed(evt);
            }
        });

        jBAcept.setText("Aceptar");
        jBAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptActionPerformed(evt);
            }
        });

        jBAtras.setText("Atrás");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        jCoBSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M", "NB" }));
        jCoBSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoBSexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabNomin)
                                    .addGap(27, 27, 27)
                                    .addComponent(jTexNomin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabAp1)
                                        .addComponent(jLabSex))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCoBSex, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTexAp1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabAp2)
                                    .addComponent(jLabEdad)
                                    .addComponent(jLabIRPF))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTexEd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jTexIRPF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTexAp2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabNom)
                        .addGap(34, 34, 34)
                        .addComponent(jTexNom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabNom)
                    .addComponent(jTexNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabAp1)
                    .addComponent(jLabAp2)
                    .addComponent(jTexAp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexAp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabSex)
                    .addComponent(jLabEdad)
                    .addComponent(jTexEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCoBSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabIRPF)
                    .addComponent(jLabNomin)
                    .addComponent(jTexNomin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexIRPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAtras)
                    .addComponent(jBAcept)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexNomActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
    this.setVisible(false);
    vAnterior.setLocationRelativeTo(null);
    vAnterior.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jBAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptActionPerformed
    admin.guardarGerente(jTexNom.getText(),jTexAp1.getText(),jTexAp2.getText(),
                        jCoBSex.getSelectedItem().toString(),jTexEd.getText(),jTexNomin.getText(),
                        jTexIRPF.getText());
    JOptionPane.showMessageDialog(null,"Se ha añadidio al gerente.");
    this.setVisible(false);
    vAnterior.setLocationRelativeTo(null);
    vAnterior.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBAceptActionPerformed

    private void jCoBSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoBSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCoBSexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAcept;
    private javax.swing.JButton jBAtras;
    private javax.swing.JComboBox<String> jCoBSex;
    private javax.swing.JLabel jLabAp1;
    private javax.swing.JLabel jLabAp2;
    private javax.swing.JLabel jLabEdad;
    private javax.swing.JLabel jLabIRPF;
    private javax.swing.JLabel jLabNom;
    private javax.swing.JLabel jLabNomin;
    private javax.swing.JLabel jLabSex;
    private javax.swing.JTextField jTexAp1;
    private javax.swing.JTextField jTexAp2;
    private javax.swing.JTextField jTexEd;
    private javax.swing.JTextField jTexIRPF;
    private javax.swing.JTextField jTexNom;
    private javax.swing.JTextField jTexNomin;
    // End of variables declaration//GEN-END:variables
}
